server:
  port: 8080

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 100
            redis-rate-limiter.burstCapacity: 100
            redis-rate-limiter.requestedTokens: 1
            key-resolver: "#{@ipKeyResolver}"
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/orders/**
        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/api/reviews/**
        - id: checkout-service
          uri: lb://checkout-service
          predicates:
            - Path=/api/checkout/**
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/customers/**
        - id: auth-service
          uri: lb://api-gateway
          predicates:
            - Path=/api/auth/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
